// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SobeSobe.Infrastructure.Data;

#nullable disable

namespace SobeSobe.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260202132251_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("SobeSobe.Core.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentDealerPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentRoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WinnerUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("WinnerUserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.Hand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Cards");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialCardsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("InitialCards");

                    b.Property<Guid>("PlayerSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerSessionId");

                    b.HasIndex("RoundId", "PlayerSessionId")
                        .IsUnique();

                    b.ToTable("Hands");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.PlayerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveRoundsOut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "Position")
                        .IsUnique();

                    b.HasIndex("GameId", "UserId");

                    b.ToTable("PlayerSessions");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentTrickNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DealerUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartyPlayerUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrickValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrumpSelectedBeforeDealing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrumpSuit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DealerUserId");

                    b.HasIndex("PartyPlayerUserId");

                    b.HasIndex("Status");

                    b.HasIndex("GameId", "RoundNumber");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.ScoreHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PointsAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsChange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RoundId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerSessionId");

                    b.HasIndex("RoundId");

                    b.ToTable("ScoreHistories");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.Trick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardsPlayedJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CardsPlayed");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LeadPlayerSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrickNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WinnerPlayerSessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeadPlayerSessionId");

                    b.HasIndex("WinnerPlayerSessionId");

                    b.HasIndex("RoundId", "TrickNumber")
                        .IsUnique();

                    b.ToTable("Tricks");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalGamesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPointsScored")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrizeWon")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalWins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.Game", b =>
                {
                    b.HasOne("SobeSobe.Core.Entities.User", "CreatedBy")
                        .WithMany("CreatedGames")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SobeSobe.Core.Entities.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerUserId");

                    b.Navigation("CreatedBy");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.Hand", b =>
                {
                    b.HasOne("SobeSobe.Core.Entities.PlayerSession", "PlayerSession")
                        .WithMany("Hands")
                        .HasForeignKey("PlayerSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SobeSobe.Core.Entities.Round", "Round")
                        .WithMany("Hands")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerSession");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.PlayerSession", b =>
                {
                    b.HasOne("SobeSobe.Core.Entities.Game", "Game")
                        .WithMany("PlayerSessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SobeSobe.Core.Entities.User", "User")
                        .WithMany("PlayerSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.Round", b =>
                {
                    b.HasOne("SobeSobe.Core.Entities.User", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SobeSobe.Core.Entities.Game", "Game")
                        .WithMany("Rounds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SobeSobe.Core.Entities.User", "PartyPlayer")
                        .WithMany()
                        .HasForeignKey("PartyPlayerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("Game");

                    b.Navigation("PartyPlayer");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.ScoreHistory", b =>
                {
                    b.HasOne("SobeSobe.Core.Entities.Game", "Game")
                        .WithMany("ScoreHistory")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SobeSobe.Core.Entities.PlayerSession", "PlayerSession")
                        .WithMany("ScoreHistory")
                        .HasForeignKey("PlayerSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SobeSobe.Core.Entities.Round", "Round")
                        .WithMany("ScoreHistory")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Game");

                    b.Navigation("PlayerSession");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.Trick", b =>
                {
                    b.HasOne("SobeSobe.Core.Entities.PlayerSession", "LeadPlayer")
                        .WithMany()
                        .HasForeignKey("LeadPlayerSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SobeSobe.Core.Entities.Round", "Round")
                        .WithMany("Tricks")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SobeSobe.Core.Entities.PlayerSession", "WinnerPlayer")
                        .WithMany()
                        .HasForeignKey("WinnerPlayerSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LeadPlayer");

                    b.Navigation("Round");

                    b.Navigation("WinnerPlayer");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.Game", b =>
                {
                    b.Navigation("PlayerSessions");

                    b.Navigation("Rounds");

                    b.Navigation("ScoreHistory");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.PlayerSession", b =>
                {
                    b.Navigation("Hands");

                    b.Navigation("ScoreHistory");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.Round", b =>
                {
                    b.Navigation("Hands");

                    b.Navigation("ScoreHistory");

                    b.Navigation("Tricks");
                });

            modelBuilder.Entity("SobeSobe.Core.Entities.User", b =>
                {
                    b.Navigation("CreatedGames");

                    b.Navigation("PlayerSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
